version: "3.9"

services:
  milliyplatform:
    container_name: milliy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5090:5090"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5090
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - /home/deploy/milliy/src/MilliyMock.Api/wwwroot:/app/wwwroot